### ISSUE TITLE
Sennarth, the Cold Breath

### ISSUE THREAD

**Issue by LootFever** [Cilraaz/LootSpecSwapper#3]
It seems to not work on Sennarth, the Cold Breath in VOTI.
Seen it on multiple toons this week showing off-spec rolls even though the correct loot-spec was set via the addon.
Sadly I couldn't check if the addon even set the loot-spec when engaging the boss.

I know AlterEgo also had a problem with this boss.
Maybe its some encounter ID stuff.

**Comment by fzarr** [comment]
Had this problem too, you can add 
`["Sennarth"] = "Sennarth, The Cold Breath",`
to the LootSpecSwapper.lua file as a temporary fix.

**Comment by Cilraaz** [comment]
This has been merged into version 10.2.7.01. Thank you for the report!
