### ISSUE TITLE
Scalecommander Sarkareth

### ISSUE THREAD

**Issue by fzarr** [Cilraaz/LootSpecSwapper#4]
Dungeon Journal name is Scalecommander Sarkareth but mobname is Sarkareth.

**Comment by fzarr** [comment]
Temp fix, add 
`["Sarkareth"] = "Scalecommander Sarkareth",`
to LootSpecSwapper.lua

**Comment by Cilraaz** [comment]
This has been merged into version 10.2.7.01. Thank you for the report!
